# MongoDB Docker Compose
# filepath: d:\AI Business Agent\ai-agentic-product\database\mongo\docker-compose.yml
version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"